services:
  app:
    container_name: notification-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
    depends_on:
      - mongodb
      - rabbitmq
    env_file:
      - .env
    networks:
      - backend

  mongodb:
    container_name: mongo
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
